apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::805160322688:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-ThjPML283Jpe
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
       - default-trainee 
    - userarn: arn:aws:iam::805160322688:user/shrihan
      username: shrihan
       
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-14T09:43:32Z"
  name: aws-auth
  namespace: kube-system
  uid: 1778c194-e5eb-4132-9a64-541972d93d83
